apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: prometheus-general.rules
  namespace: monitoring
spec:
  groups:
  - name: monitoring-kube-kube-prometheus-general.rules
    rules:
    - expr: count without(instance, pod, node) (up == 1)
      record: count:up1
    - expr: count without(instance, pod, node) (up == 0)
      record: count:up0
