apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubernetes-apps-high-rules
  namespace: monitoring 
spec:
  groups:
  - name: kubernetes-apps
    rules:
    # - alert: KubePodRestarting
    #   annotations:
    #     description: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
    #     runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
    #     summary: Pod is Restarting.
    #     dashboard_url: https://grafana-internal.stablemoney.in/explore
    #   expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace=~".*"}[5m]) * 60 * 5 > 2
    #   labels:
    #     severity: warning
    #     channel: slack
    #     team: devops

    - alert: KubePodNotReady 
      annotations:
        description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 5 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
        summary: Pod has been in a non-ready state for more than 10 minutes.
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        sum by (namespace, pod) (
          max by(namespace, pod) (
            kube_pod_status_phase{job="kube-state-metrics", namespace=~".*", phase=~"Pending|Unknown"}
          ) * on(namespace, pod) group_left(owner_kind) topk by(namespace, pod) (
            1, max by(namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"})
          )
        ) > 0
      for: 10m
      labels:
        severity: warning
        channel: slack
        team: devops

    - alert: KubeDeploymentGenerationMismatch 
      annotations:
        description: Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment }} does not match, this indicates that the Deployment has failed but has not been rolled back.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch
        summary: Deployment generation mismatch due to possible roll-back
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        kube_deployment_status_observed_generation{job="kube-state-metrics", namespace=~".*"}
          !=
        kube_deployment_metadata_generation{job="kube-state-metrics", namespace=~".*"}
      for: 5m
      labels:
        severity: warning
        channel: slack
        team: devops
        
    - alert: KubeDeploymentReplicasMismatch 
      annotations:
        description: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number of replicas for longer than 5 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentreplicasmismatch
        summary: Deployment has not matched the expected number of replicas.
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        (
          kube_deployment_spec_replicas{job="kube-state-metrics", namespace=~".*"}
            !=
          kube_deployment_status_replicas_available{job="kube-state-metrics", namespace=~".*"}
        ) and (
          changes(kube_deployment_status_replicas_updated{job="kube-state-metrics", namespace=~".*"}[5m])
            ==
          0
        )
      for: 5m
      labels:
        severity: warning
        channel: slack
        team: devops
        
    - alert: KubeStatefulSetReplicasMismatch 
      annotations:
        description: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} has not matched the expected number of replicas for longer than 5 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetreplicasmismatch
        summary: Deployment has not matched the expected number of replicas.
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        (
          kube_statefulset_status_replicas_ready{job="kube-state-metrics", namespace=~".*"}
            !=
          kube_statefulset_status_replicas{job="kube-state-metrics", namespace=~".*"}
        ) and (
          changes(kube_statefulset_status_replicas_updated{job="kube-state-metrics", namespace=~".*"}[5m])
            ==
          0
        )
      for: 5m
      labels:
        severity: warning
        channel: slack
        team: devops
        
    - alert: KubeStatefulSetGenerationMismatch 
      annotations:
        description: StatefulSet generation for {{ $labels.namespace }}/{{ $labels.statefulset }} does not match, this indicates that the StatefulSet has failed but has not been rolled back.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetgenerationmismatch
        summary: StatefulSet generation mismatch due to possible roll-back
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        kube_statefulset_status_observed_generation{job="kube-state-metrics", namespace=~".*"}
          !=
        kube_statefulset_metadata_generation{job="kube-state-metrics", namespace=~".*"}
      for: 5m
      labels:
        severity: warning
        channel: slack
        team: devops
        
    - alert: KubeStatefulSetUpdateNotRolledOut 
      annotations:
        description: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} update has not been rolled out.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetupdatenotrolledout
        summary: StatefulSet update has not been rolled out.
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        (
          max without (revision) (
            kube_statefulset_status_current_revision{job="kube-state-metrics", namespace=~".*"}
              unless
            kube_statefulset_status_update_revision{job="kube-state-metrics", namespace=~".*"}
          )
            *
          (
            kube_statefulset_replicas{job="kube-state-metrics", namespace=~".*"}
              !=
            kube_statefulset_status_replicas_updated{job="kube-state-metrics", namespace=~".*"}
          )
        )  and (
          changes(kube_statefulset_status_replicas_updated{job="kube-state-metrics", namespace=~".*"}[5m])
            ==
          0
        )
      for: 5m
      labels:
        severity: warning
        channel: slack
        team: devops
        
    - alert: KubeDaemonSetRolloutStuck 
      annotations:
        description: DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} has not finished or progressed for at least 5 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetrolloutstuck
        summary: DaemonSet rollout is stuck.
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        (
          (
            kube_daemonset_status_current_number_scheduled{job="kube-state-metrics", namespace=~".*"}
            !=
            kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"}
          ) or (
            kube_daemonset_status_number_misscheduled{job="kube-state-metrics", namespace=~".*"}
            !=
            0
          ) or (
            kube_daemonset_updated_number_scheduled{job="kube-state-metrics", namespace=~".*"}
            !=
            kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"}
          ) or (
            kube_daemonset_status_number_available{job="kube-state-metrics", namespace=~".*"}
            !=
            kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"}
          )
        ) and (
          changes(kube_daemonset_updated_number_scheduled{job="kube-state-metrics", namespace=~".*"}[5m])
            ==
          0
        )
      for: 5m
      labels:
        severity: warning
        channel: slack
        team: devops
        
    - alert: KubeContainerWaiting 
      annotations:
        description: Pod {{ $labels.namespace }}/{{ $labels.pod }} container {{ $labels.container}} has been in waiting state for longer than 0.5 hour.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontainerwaiting
        summary: Pod container waiting longer than 0.5 hour
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: sum by (namespace, pod, container) (kube_pod_container_status_waiting_reason{job="kube-state-metrics", namespace=~".*"}) > 0
      for: 30m
      labels:
        severity: warning
        channel: slack
        team: devops
        
    - alert: KubeDaemonSetNotScheduled 
      annotations:
        description: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are not scheduled.'
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetnotscheduled
        summary: DaemonSet pods are not scheduled.
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"}
          -
        kube_daemonset_status_current_number_scheduled{job="kube-state-metrics", namespace=~".*"} > 0
      for: 5m
      labels:
        severity: warning
        channel: slack
        team: devops
        
    - alert: KubeDaemonSetMisScheduled 
      annotations:
        description: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are running where they are not supposed to run.'
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetmisscheduled
        summary: DaemonSet pods are misscheduled.
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: kube_daemonset_status_number_misscheduled{job="kube-state-metrics", namespace=~".*"} > 0
      for: 5m
      labels:
        severity: warning
        channel: slack
        team: devops
    - alert: PodHighCpuUsageWarning
      annotations:
        description: "Pod {{ $labels.pod }} is using more than 70% of CPU."
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
        summary: "Warning: Pod CPU usage is high."
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        (
          sum(rate(container_cpu_usage_seconds_total{namespace=~".*", container!="POD", container!="", pod!=""}[5m])) by (namespace, pod)
          ) /
        (
          sum(kube_pod_container_resource_limits{namespace=~".*", pod=~".*", resource="cpu"}) by (namespace, pod)
          ) * 100 > 70

      labels:
        severity: warning
        channel: slack
        team: devops
    - alert: PodHighMemoryUsageWarning
      annotations:
        description: "Pod {{ $labels.pod }} is using more than 70% of memory. "
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
        summary: "Warning: Pod memory usage is high."
        dashboard_url: https://grafana-internal.stablemoney.in/explore
      expr: |-
        (
         sum(rate(container_memory_usage_bytes{namespace=~".*", container!="POD", container!="", pod!=""}[5m])) by (namespace, pod)
         ) /
        (
         sum(kube_pod_container_resource_limits{namespace=~".*", pod=~".*", resource="memory"}) by (namespace, pod)
         ) * 100 > 70
      labels:
        severity: warning
        channel: slack
        team: devops
        
    # - alert: KubeJobCompletion 
    #   annotations:
    #     description: Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than 6 hours to complete.
    #     runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobcompletion
    #     summary: Job did not complete in time
    #     dashboard_url: https://grafana-internal.stablemoney.in/explore
    #   expr: kube_job_spec_completions{job="kube-state-metrics", namespace=~".*"} - kube_job_status_succeeded{job="kube-state-metrics", namespace=~".*"}  > 0
    #   for: 6h
    #   labels:
    #     severity: warning
    #     channel: slack
    #     team: devops

    # - alert: KubeJobFailed 
    #   annotations:
    #     description: Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete.
    #     runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobfailed
    #     summary: Job failed to complete.
    #     dashboard_url: https://grafana-internal.stablemoney.in/explore
    #   expr: kube_job_failed{job="kube-state-metrics", namespace=~".*"}  > 0
    #   for: 5m
    #   labels:
    #     severity: high
    #     channel: slack
    #     team: devops
#    - alert: KubeHpaReplicasMismatch 
#      annotations:
#        description: HPA {{ $labels.namespace }}/{{ $labels.hpa }} has not matched the desired number of replicas for longer than 5 minutes.
#        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubehpareplicasmismatch
#        summary: HPA has not matched desired number of replicas.
#      expr: |-
#        (kube_hpa_status_desired_replicas{job="kube-state-metrics", namespace=~".*"}
#          !=
#        kube_hpa_status_current_replicas{job="kube-state-metrics", namespace=~".*"})
#          and
#        changes(kube_hpa_status_current_replicas[15m]) == 0
#      for: 15m
#      labels:
#        severity: high
#        channel: slack
#        team: devops
    # - alert: KubeHpaMaxedOut 
    #   annotations:
    #     description: HPA {{ $labels.namespace }}/{{ $labels.hpa }} has been running at max replicas for longer than 5 minutes.
    #     runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubehpamaxedout
    #     summary: HPA is running at max replicas
    #   expr: |-
    #     kube_hpa_status_current_replicas{job="kube-state-metrics", namespace=~".*"}
    #       ==
    #     kube_hpa_spec_max_replicas{job="kube-state-metrics", namespace=~".*"}
    #   for: 5m
    #   labels:
    #     severity: high
    #     channel: slack
    #     team: devops
    - alert: KubePodRestartingOOM 
      expr: kube_pod_container_status_terminated_reason{reason="OOMKilled"} > 0
      labels:
        severity: warning
        channel: slack
        team: devops
      annotations:
        message: "Pod {{$labels.pod}} in namespace {{$labels.namespace}} in terminated status"
        description: 'Pod {{$labels.pod}} in namespace {{$labels.namespace}} has a container terminated for more than 1 minute'
        dashboard_url: https://grafana-internal.stablemoney.in/explore
        summary: "Pod Container OOMKilled Detected"
    # - alert: KubePodCrashLoopBackOff 
    #   expr: rate(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[3m]) * 60 * 3 > 0
    #   labels:
    #     severity: warning
    #     channel: slack
    #     team: devops
    #   annotations:
    #     message: "Pod {{$labels.pod}} in namespace {{$labels.namespace}} in CrashLoopBackOff status"
    #     description: 'Pod {{$labels.pod}} in namespace {{$labels.namespace}} has a container in CrashLoopBackOff for more than 3 minute'
    #     dashboard_url: https://grafana-internal.stablemoney.in/explore
    #     summary: "Pod in CrashLoopBackOff Detected"
    - alert: KubePodImagePullBackOff 
      expr: rate(kube_pod_container_status_waiting_reason{reason="ImagePullBackOff"}[3m]) * 60 * 3 > 0
      labels:
        severity: warning
        channel: slack
        team: devops
      annotations:
        message: "Pod {{$labels.pod}} in namespace {{$labels.namespace}} in ImagePullBackOff status"
        description: 'Pod {{$labels.pod}} in namespace {{$labels.namespace}} has a container in ImagePullBackOff for more than 3 minute'
        dashboard_url: https://grafana-internal.stablemoney.in/explore
        summary: "Pod ImagePullBackOff Detected"
