apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: buildpiper-storage
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3  # or "gp3" for improved performance
  fsType: ext4
  encrypted: "true"  # Enables encryption for the volume

