apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: general-rules
  namespace: monitoring 
spec:
  groups:
  - name: general.rules
    rules:
    - alert: TargetDown 
      annotations:
        description: '{{ printf "%.4g" $value }}% of the {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are down.'
        runbook_url:  https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
        dashboard_url: https://grafana-internal.stablemoney.in/explore
        summary: "Some targets are down"
      expr: 100 * (count(up{namespace!="kube-system"}  == 0) BY (job, namespace, service) / count(up) BY (job, namespace, service)) > 10
      for: 10m
      labels:
        severity: warning
        channel: slack
        team: devops
    # - alert: Watchdog 
    #   annotations:
    #     description: |
    #       This is an alert meant to ensure that the entire alerting pipeline is functional.
    #       This alert is always firing, therefore it should always be firing in Alertmanager
    #       and always fire against a receiver. There are integrations with various notification
    #       mechanisms that send a notification when this alert is not firing. For example the
    #       "DeadMansSnitch" integration in PagerDuty.
    #     runbook_url: 
    #     dashboard_url: https://grafana-internal.stablemoney.in/explore
    #     summary: "Ensure alerting pipeline functionality"
    #   expr: vector(1)
    #   labels:
    #     severity: none
    #     team: devops
    #     channel: slack
