# apiVersion: operator.victoriametrics.com/v1beta1
# kind: VMRule
# metadata:
#   name: prometheus-operator-rules
#   namespace: monitoring 
# spec:
#   groups:
#   - name: prometheus-operator
#     rules:
#     - alert: PrometheusOperatorListErrors 
#       annotations:
#         description: Errors while performing List operations in controller {{$labels.controller}} in {{$labels.namespace}} namespace.
#         runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-prometheusoperatorlisterrors
#         summary: Errors while performing list operations in controller.
#         dashboard_url: https://grafana-internal.stablemoney.in/explore
#       expr: (sum by (controller,namespace) (rate(prometheus_operator_list_operations_failed_total{job="kube-operator",namespace="monitoring"}[10m])) / sum by (controller,namespace) (rate(prometheus_operator_list_operations_total{job="kube-operator",namespace="monitoring"}[10m]))) > 0.4
#       for: 15m
#       labels:
#         severity: warning
#         channel: slack
#         team: devops
#     - alert: PrometheusOperatorWatchErrors 
#       annotations:
#         description: Errors while performing watch operations in controller {{$labels.controller}} in {{$labels.namespace}} namespace.
#         runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-prometheusoperatorwatcherrors
#         summary: Errors while performing watch operations in controller.
#         dashboard_url: https://grafana-internal.stablemoney.in/explore
#       expr: (sum by (controller,namespace) (rate(prometheus_operator_watch_operations_failed_total{job="kube-operator",namespace="monitoring"}[10m])) / sum by (controller,namespace) (rate(prometheus_operator_watch_operations_total{job="kube-operator",namespace="monitoring"}[10m]))) > 0.4
#       for: 15m
#       labels:
#         severity: warning
#         channel: slack
#         team: devops
#     - alert: PrometheusOperatorReconcileErrors 
#       annotations:
#         description: '{{ $value | humanizePercentage }} of reconciling operations failed for {{ $labels.controller }} controller in {{ $labels.namespace }} namespace.'
#         runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-prometheusoperatorreconcileerrors
#         summary: Errors while reconciling controller.
#         dashboard_url: https://grafana-internal.stablemoney.in/explore
#       expr: (sum by (controller,namespace) (rate(prometheus_operator_reconcile_errors_total{job="kube-operator",namespace="monitoring"}[5m]))) / (sum by (controller,namespace) (rate(prometheus_operator_reconcile_operations_total{job="kube-operator",namespace="monitoring"}[5m]))) > 0.1
#       for: 10m
#       labels:
#         severity: warning
#         channel: slack
#         team: devops
#     - alert: PrometheusOperatorNodeLookupErrors 
#       annotations:
#         description: Errors while reconciling Prometheus in {{ $labels.namespace }} Namespace.
#         runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-prometheusoperatornodelookuperrors
#         summary: Errors while reconciling Prometheus.
#         dashboard_url: https://grafana-internal.stablemoney.in/explore
#       expr: rate(prometheus_operator_node_address_lookup_errors_total{job="kube-operator",namespace="monitoring"}[5m]) > 0.1
#       for: 10m
#       labels:
#         severity: warning
#         channel: slack
#         team: devops
